export enum ESize {
  XSS = 'XSS',
  XS = 'XS',
  SM = 'SM',
  MD = 'MD',
  LG = 'LG',
  XL = 'XL',
  XXL = 'XXL',
  X2 = '2X',
  X3 = '3X',
  X4 = '4X',
  X5 = '5X',
  OX = 'OX',
  ONE = 'ONE'
}
export enum EWaist {
  w23 = '23',
  w24 = '24',
  w25 = '25',
  w26 = '26',
  w27 = '27',
  w28 = '28',
  w29 = '29',
  w30 = '30',
  w31 = '31',
  w32 = '32',
  w33 = '33',
  w34 = '34',
  w35 = '35',
  w36 = '36',
  w37 = '37',
}
export enum ECategory {
  Women = 'Women',
  Clothing = 'Clothing',
  Dresses = 'Dresses',
  Tops = 'Tops',
  Sweaters = 'Sweaters',
  Jackets = 'Jackets',
  Jeans = 'Jeans',
  Pants = 'Pants',
  Shorts = 'Shorts',
  Skirts = 'Skirts',
  Swimwear = 'Swimwear',
  Sportswear = 'Sportswear',
  Etc = 'Etc',  
}
export const ESearchPeriod = [
  {key: 'All', value: 9999},
  {key: 'Today', value: 0},
  {key: 'Yesterday', value: 1},
  {key: 'Last 2 days', value: 2},
  {key: 'Last 7 days', value: 7},
  {key: 'Last 30 days', value: 30},
  {key: 'Last 2 months', value: 60},
  {key: 'Last 6 months', value: 180},
  {key: 'Last year', value: 365}
]

export const APrice = [
  { key: 'Under $10', value: '0, 10' },
  { key: '$10 - $25', value: '10, 25' },
  { key: '$25 - $50', value: '25, 50' },
  { key: '$50 - $150', value: '50, 150' },
  { key: '$150 - $500', value: '150, 500' },
  { key: '$500 - $10,000', value: '500, 10000' },
]

export enum ECondition {
  New = 'New',
  LikeNew = 'Like New',
  Used = 'Used',
  GentlyUsed = 'Gently Used',
  SignOfWear = 'Sign of Wear',
}

export const EMaterial = [
  { key: 'Cotton', value: false },
  { key: 'Polyester', value: false },
  { key: 'Rayon', value: false },
  { key: 'Spandex', value: false },
  { key: 'Silk', value: false },
  { key: 'Wool', value: false },
  { key: 'Linen', value: false },
  { key: 'Leather', value: false },
  { key: 'Denim', value: false },
  { key: 'Lace', value: false },
  { key: 'Velvet', value: false },
  { key: 'Faux Leather', value: false },
  { key: 'Cashmere', value: false },
  { key: 'Acrylic', value: false },
  { key: 'Nylon', value: false },
]
export enum EMaterial2 {
  Cotton = 'Cotton',
  Polyester = 'Polyester',
  Rayon = 'Rayon',
  Spandex = 'Spandex',
  Silk = 'Silk',
  Wool = 'Wool',
  Linen = 'Linen',
  Leather = 'Leather',
  Denim = 'Denim',
  Lace = 'Lace',
  Velvet = 'Velvet',
  FauxLeather = 'Faux Leather',
  Cashmere = 'Cashmere',
  Acrylic = 'Acrylic',
  Nylon = 'Nylon',
}

export enum EPattern {
  AnimalPrint = 'Animal Print',
  Floral = 'Floral',
  Striped = 'Striped',
  Tweed = 'Tweed',
  Tropical = 'Tropical',
  Solid = 'Solid',
  Plaid = 'Plaid',
  Paisley = 'Paisley',
  Graphic = 'Graphic',
  Geometric = 'Geometric',
  Embroidered = 'Embroidered',
  Sequined = 'Sequined',
  Lace = 'Lace',
  Ruched = 'Ruched',
  Ripped = 'Ripped',
  Distressed = 'Distressed',
  TieDye = 'Tie Dye',
  Sheer = 'Sheer',
  Mesh = 'Mesh',
  Metallic = 'Metallic',
  Beaded = 'Beaded',
  Embellished = 'Embellished',
  Cutout = 'Cutout',
  Frayed = 'Frayed',
  Pleated = 'Pleated',
  Tassel = 'Tassel',
  Tulle = 'Tulle',
  Velvet = 'Velvet',
  FauxLeather = 'Faux Leather',
}